### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by karhtickvalentino** [m3nu/invoice2data#105]
Hi,
I have installed all the packages necessary. When I try to run the build in PDFs, I get the correct output. How should I run my PDFs. When i run my PDF I get : ERROR:invoice2data.main:No template for invoice.pdf.
How should I specify the templete to be used for specific invoices.

Thanks

**Comment by m3nu** [comment]
This means that your invoice isn't covered in a template yet. You are welcome to add one or post it here, so someone else can create a template.

**Comment by karhtickvalentino** [comment]
The invoice format is different for every customer. So Should I create a template for every new format?

**Comment by m3nu** [comment]
Generally every company has _one_ invoice template. I didn't see a case where they redid the invoice for each customer...? By this I mean that address, date, total will be in the same place, while the individual fields and items are different of course.

**Comment by karhtickvalentino** [comment]
Can you please give me the template for the below PDF. So i will get better at designing template.
Thanks.
![invoice_demo](https://user-images.githubusercontent.com/28265412/38303375-87081200-3823-11e8-883c-c4f0a56a562e.png)

**Comment by m3nu** [comment]
You can look at existing templates to learn about it. There are almost 100 available by now contributed by different people and companies.

If your company needs specific templates added, they should hire a developer to carry out the work. As an open source project we are mainly interested in improving the underlying library, rather than implementing specific business cases.
