### ISSUE TITLE
Match language in addition to tax number

### ISSUE THREAD

**Issue by m3nu** [m3nu/invoice2data#13]
Ran into an issue with your `fr35433115904.yml` Scaleway template. First it's nice to be able to use other people's templates. But you are matching the French version. I guess each template needs one word under `keywords` to match the right version?

**Comment by m3nu** [comment]
Also using domains + language code may scale better than naming templates by tax ID.

**Comment by m3nu** [comment]
@alexis-via  ^^

**Comment by alexis-via** [comment]
Yes, I fully agree with you, and that's precisely why I implemented the multi-keyword feature, because I feelt that we would face this problem very soon ! And now we are there :)

As you can see in the subdirectoy "fr", I am in the process of renaming the template files and adding more keywords to only match the French version of the invoice (and also add the issuer entry and the options). But, as I have many templates, it takes time. I was working on it yesterday evening, and that's how I found the "float" issue :) I'll fix the float issue first, and then I'll continue to update the fr templates (in that order, because if we add the new options for decimal and thousand separator, I'll have to update and test all the templates again !)

P.S. : in my last commit, I updated the fr35433115904.yml template to the new format.
