### ISSUE TITLE
Export multiple output formats, like json, csv

### ISSUE THREAD

**Issue by maethor** [m3nu/invoice2data#34]
Hi,

I know we can use invoice2data directly as a lib in python, but it would be great to make the output parsable. With a `--json` parameter, for instance.

Thanks, this app is awesome.

**Comment by m3nu** [comment]
We already support outputting structured fields as CSV. And the library uses dicts/json internally.

So adding a `--json` parameter would make sense to integrate with other (non-Python) tools.

**Comment by m3nu** [comment]
Custom CSV name is possible now, but people want more formats. What's needed? CSV, JSON, ..? @duskybomb

**Comment by duskybomb** [comment]
How about XML and cXML @m3nu?

**Comment by m3nu** [comment]
If you use XML, go ahead.

Since people want all kinds of crazy extensions, I see a modular workflow in the future. Where each step can be done using different modules/plugins:

1. Extract text (OCR, pdf2text)
2. Pre-process (remove white space, lower case, ...)
3. Extract matches using templates – no modules there I guess
4. Output (rename file, csv, json, xml, other crazy stuff)

**Comment by rsenwar** [comment]
json output format added #73

**Comment by m3nu** [comment]
Solved. Thanks @rsenwar
